# Generated by Django 3.2.5 on 2023-12-15 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20231215_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_lawyer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_translator',
            field=models.BooleanField(default=False),
        ),
    ]
